### ISSUE TITLE
Android Renderer is missing

### ISSUE THREAD

**Issue by edljoko** [PieEatingNinjas/HyperlinkLabel#1]
Hi It works great for iOS but I can't run the app in Android. I have checked your project and couldn't find the renderer for android. Can you please add it? Thanks

**Comment by PieEatingNinjas** [comment]
Hi @bastianbecker21 ! That's indeed correct. I haven't yet implemented this on Android. But, since I put this source on GitHub, I had many people asking for it.
Keep an eye on this project, because I will start looking at it soon.

**Comment by edljoko** [comment]
Hi @PieEatingNinjas , I need it in 2~3 days. If you can't add it for that time, I need to find another solution. Please let me know your opinion, Thanks. iOS works really good as EXPECTED!!!

**Comment by PieEatingNinjas** [comment]
I should have some time over the weekend. I don't expect the Android implementation to be hard.  I'll see what I can do.

**Comment by edljoko** [comment]
Ok Thanks, I will wait for your Android implementation then. Please let me know when you complete.
This is great help for me!

**Comment by PieEatingNinjas** [comment]
@bastianbecker21 I had some time during lunch. I've create a separate branch which contains an Android renderer. Is this the solution you are looking for? I've tested it, and it seems to work. If you can test this as well and confirm that it also works for your scenario, I can merge this to master for everyone to enjoy ;-)
